ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'DOWNLOAD';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'PREVIEW';
ALTER TYPE "AttachmentStorageProvider" ADD VALUE IF NOT EXISTS 'OBJECT_STORAGE';
